import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Header from '@/app/header';

const geist = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Assembly: Endgame",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geist.className}>
      <body className="bg-zinc-800 w-screen p-8 flex flex-col gap-4 items-center justify-center">
	<Header />
        {children}
      </body>
    </html>
  );
}
